# Oretty TURN Server Configuration (coturn)
listening-port=3478
tls-listening-port=5349
listening-ip=0.0.0.0
relay-ip=0.0.0.0
external-ip=161.118.185.63

realm=oretty.sametyilmaztemel.com
server-name=oretty

fingerprint
lt-cred-mech
user=oretty:EZ0Er3g4Ir5T0A7vbxYf

# Logging
verbose
log-file=/var/log/turnserver.log
simple-log

# Security
no-multicast-peers
no-tcp-relay
no-stdout-log
